services:
  verification:
    build: .
    env_file:
      - ./.env # Replace this with your env file on host.
    # expose:
    #   - "8000"
    #   - "5000"
    ports:
      - "5000:5000"
      - "7800:8000"
    volumes:
      - ./db:/app/db # Replace this with your db folder on host.
    networks:
      - proxy
    healthcheck: # AI-made healthcheck.
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000', timeout=3); urllib.request.urlopen('http://localhost:5000/verify/status/test@example.com', timeout=3)"]
      interval: 30s
      timeout: 5s
      retries: 3

    restart: unless-stopped

  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "80:80"
      - "81:81" # NPM admin panel.
      - "443:443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: verification-proxy
